version: "3"
services:
    rabbitmq:
        image: rabbitmq:management
        expose:
         - "5672"
        ports:
         - "15672:15672"
         - "5672:5672"
        deploy:
            resources:
                limits:
                    memory: 256MB
                reservations:
                    memory: 256MB
        networks:
          - default
    rabbitmq2:
        image: rabbitmq:management
        expose:
         - "5672"
        ports:
         - "15673:15672"
         - "5673:5672"
        deploy:
            resources:
                limits:
                    memory: 256MB
                reservations:
                    memory: 256MB
        networks:
          - default